global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-services'
    static_configs:
      - targets: ['api-gateway:8080', 'user-service:5000', 'content-service:5001']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
